#include "src/canvas.c"
typedef struct { int w,h,stride,fmt; void* bits; } FakeWindow;
typedef struct { int type,action,pc,button; int64_t t; float x[4],y[4],p[4]; int tool[4],id[4]; int hist;int64_t ht[8];float hx[8][4],hy[8][4],hp[8][4];} FakeEvent;
int32_t ANativeWindow_setFrameRate(ANativeWindow*w,float f,int8_t c){(void)w;(void)f;(void)c;return 0;}
int32_t ANativeWindow_lock(ANativeWindow*w,ANativeWindow_Buffer*out,ARect*r){(void)r;FakeWindow*f=(FakeWindow*)w;out->width=f->w;out->height=f->h;out->stride=f->stride;out->format=f->fmt;out->bits=f->bits;return 0;} int32_t ANativeWindow_unlockAndPost(ANativeWindow*w){(void)w;return 0;}
void ANativeActivity_setWindowFlags(ANativeActivity*a,uint32_t b,uint32_t c){(void)a;(void)b;(void)c;} ALooper* ALooper_forThread(void){return (ALooper*)1;} ALooper* ALooper_prepare(int x){(void)x;return (ALooper*)1;} int ALooper_addFd(ALooper*l,int fd,int ident,int events,int(*cb)(int,int,void*),void*d){(void)l;(void)fd;(void)ident;(void)events;(void)cb;(void)d;return 1;} void AInputQueue_attachLooper(AInputQueue*a,ALooper*b,int c,int(*d)(int,int,void*),void*e){(void)a;(void)b;(void)c;(void)d;(void)e;} void AInputQueue_detachLooper(AInputQueue*a){(void)a;} int32_t AInputQueue_getEvent(AInputQueue*a,AInputEvent**b){(void)a;(void)b;return -1;} int32_t AInputQueue_preDispatchEvent(AInputQueue*a,AInputEvent*b){(void)a;(void)b;return 0;} void AInputQueue_finishEvent(AInputQueue*a,AInputEvent*b,int c){(void)a;(void)b;(void)c;}
int32_t AInputEvent_getType(const AInputEvent*e){return ((const FakeEvent*)e)->type;} int32_t AMotionEvent_getAction(const AInputEvent*e){return ((const FakeEvent*)e)->action;} size_t AMotionEvent_getPointerCount(const AInputEvent*e){return (size_t)((const FakeEvent*)e)->pc;} float AMotionEvent_getX(const AInputEvent*e,size_t i){return ((const FakeEvent*)e)->x[i];} float AMotionEvent_getY(const AInputEvent*e,size_t i){return ((const FakeEvent*)e)->y[i];} float AMotionEvent_getPressure(const AInputEvent*e,size_t i){return ((const FakeEvent*)e)->p[i];} int32_t AMotionEvent_getPointerId(const AInputEvent*e,size_t i){return ((const FakeEvent*)e)->id[i];} int32_t AMotionEvent_getToolType(const AInputEvent*e,size_t i){return ((const FakeEvent*)e)->tool[i];} size_t AMotionEvent_getHistorySize(const AInputEvent*e){return ((const FakeEvent*)e)->hist;} float AMotionEvent_getHistoricalX(const AInputEvent*e,size_t i,size_t j){return ((const FakeEvent*)e)->hx[j][i];} float AMotionEvent_getHistoricalY(const AInputEvent*e,size_t i,size_t j){return ((const FakeEvent*)e)->hy[j][i];} float AMotionEvent_getHistoricalPressure(const AInputEvent*e,size_t i,size_t j){return ((const FakeEvent*)e)->hp[j][i];} int32_t AMotionEvent_getButtonState(const AInputEvent*e){return ((const FakeEvent*)e)->button;} int64_t AMotionEvent_getEventTime(const AInputEvent*e){return ((const FakeEvent*)e)->t*1000000LL;}
int64_t AMotionEvent_getHistoricalEventTime(const AInputEvent*e,size_t j){return ((const FakeEvent*)e)->ht[j]*1000000LL;}
AChoreographer*AChoreographer_getInstance(void){return 0;}void AChoreographer_postFrameCallback(AChoreographer*c,void(*fn)(long,void*),void*d){}
extern int printf(const char*,...); static int fail=0; static int64_t tm=10000; static void check(int c,const char*n){if(c)printf("PASS %s\n",n);else{printf("FAIL %s\n",n);fail=1;}} static void ev1(FakeEvent*e,int action,int tool,float x,float y,float p){memset(e,0,sizeof(*e));e->type=2;e->action=action;e->pc=1;e->tool[0]=tool;e->x[0]=x;e->y[0]=y;e->p[0]=p;e->t=tm+=20;}
int main(){
 ANativeActivityCallbacks cb;memset(&cb,0,sizeof(cb));ANativeActivity a;memset(&a,0,sizeof(a));a.callbacks=&cb;a.internalDataPath="./testdata30";a.sdkVersion=36;ANativeActivity_onCreate(&a,0,0);
 FakeWindow fw={1400,900,1400,1,0};fw.bits=malloc((size_t)fw.w*fw.h*4);cb.onNativeWindowCreated(&a,(ANativeWindow*)&fw);
 int rx,ry,rw,rh,rg;rail_geom(&rx,&ry,&rw,&rh,&rg);check(ry==(G.screenH-(8*rh+7*rg))/2,"8-item workspace rail centered");
 check(ui_hit(us(30),G.screenH-us(30))==UI_INK_TOGGLE,"bottom-left ink toggle is a large corner quarter-circle");
 {int wd=280;uint32_t*wb=(uint32_t*)malloc((size_t)wd*wd*4);Surf ws={(uint8_t*)wb,wd,wd,wd,FORMAT_RGBA8888};fill(&ws,C_BG);draw_picker_hs_wheel(&ws,10,10,240);uint32_t wc=getrgb(&ws,10+120+88,10+120);int wr=(wc>>16)&255,wg=(wc>>8)&255,wbv=wc&255;check(wr>wg+80&&wr>wbv+80,"Blender-style HS wheel retains saturated gamut");free(wb);}
 check(pen_hold_buffer_px()>7.9f,"dynamic radial buffer exists");float b1=pen_hold_buffer_px();G.scale=.1f;float b2=pen_hold_buffer_px();check(b2>b1,"radial tolerance grows when zoomed out");G.scale=1.0f;
 // Finger hold owns the radial menu; moving the same finger must cancel it and pan.
 G.penHoldTimerFd=timerfd_create(CLOCK_MONOTONIC,0);FakeEvent fe;float panX=G.offX,panY=G.offY;ev1(&fe,AMOTION_ACTION_DOWN,TOOL_FINGER,700,450,0);handle_motion((AInputEvent*)&fe);check(G.penHoldArmed&&G.touchHoldMode==1,"finger hold arms radial on empty canvas");ev1(&fe,AMOTION_ACTION_MOVE,TOOL_FINGER,790,510,0);handle_motion((AInputEvent*)&fe);check(G.offX>panX+50&&G.offY>panY+30,"one-finger drag pans canvas");check(!G.penHoldArmed,"finger pan cancels radial hold");ev1(&fe,AMOTION_ACTION_UP,TOOL_FINGER,790,510,0);handle_motion((AInputEvent*)&fe);check(G.flingActive&&G.flingVX>0&&G.flingVY>0,"fling follows timestamped release velocity");fling_cancel();
 G.zenMode=1;G.railOpen=0;G.minimap=1;float focusX=G.offX,focusY=G.offY;ev1(&fe,AMOTION_ACTION_DOWN,TOOL_FINGER,G.screenW-60,G.screenH-60,0);handle_motion((AInputEvent*)&fe);check(G.zenMode&&!G.railOpen,"empty-canvas finger down keeps chrome hidden");ev1(&fe,AMOTION_ACTION_MOVE,TOOL_FINGER,G.screenW-130,G.screenH-120,0);handle_motion((AInputEvent*)&fe);check(G.fingerPanning&&fabsf(G.offX-focusX)>40&&fabsf(G.offY-focusY)>35,"focus mode one-finger drag pans over hidden minimap region");ev1(&fe,AMOTION_ACTION_UP,TOOL_FINGER,G.screenW-130,G.screenH-120,0);handle_motion((AInputEvent*)&fe);check(G.zenMode&&!G.railOpen,"empty-canvas pan never reveals chrome");fling_cancel();ev1(&fe,AMOTION_ACTION_DOWN,TOOL_FINGER,G.screenW-60,G.screenH-60,0);handle_motion((AInputEvent*)&fe);ev1(&fe,AMOTION_ACTION_UP,TOOL_FINGER,G.screenW-60,G.screenH-60,0);handle_motion((AInputEvent*)&fe);check(!G.zenMode&&!G.railOpen,"stationary empty-canvas tap restores compact chrome");
 FakeEvent reordered;memset(&reordered,0,sizeof(reordered));reordered.pc=2;reordered.id[0]=20;reordered.id[1]=10;G.fingerId0=10;G.fingerId1=20;int pi0=-1,pi1=-1;check(finger_pair_indices((AInputEvent*)&reordered,2,&pi0,&pi1)&&pi0==1&&pi1==0,"two-finger gestures track stable pointer IDs across index reorder");
 // Stylus contact must never arm the radial menu.
 G.tool=MODE_SELECT;cancel_pen_hold_timer();ev1(&fe,AMOTION_ACTION_DOWN,TOOL_STYLUS,1000,650,.5f);handle_motion((AInputEvent*)&fe);check(!G.penHoldArmed&&G.touchHoldMode==0,"stylus does not arm radial menu");ev1(&fe,AMOTION_ACTION_UP,TOOL_STYLUS,1000,650,.5f);handle_motion((AInputEvent*)&fe);G.tool=MODE_PEN;
 // Frame creation / persistence
 G.offX=0;G.offY=0;G.scale=1.0f;G.liveFrame=(FrameObj){100,120,400,260,0,0,1};frame_add_live();check(G.frameN==1&&G.selectedFrame==0,"frame creation");check(frame_contents_count(&G.frames[0])==0,"empty frame contents count");
 float fw0=G.frames[0].w,fh0=G.frames[0].h;frame_resize_begin(2);frame_resize_to(G.frames[0].x+fw0+120,G.frames[0].y+fh0+80);G.frameResizeDragging=0;check(G.frames[0].w>fw0+100&&G.frames[0].h>fh0+60,"frame corner resize is live");G.frameSizeLocked[0]=1;float brx=(G.frames[0].x+G.frames[0].w)*G.scale+G.offX,bry=(G.frames[0].y+G.frames[0].h)*G.scale+G.offY;check(frame_corner_hit(brx,bry)<0,"frame size lock disables corner resize");
 int sid=start_stroke(220,220,.5f);add_stroke_point(260,250,.5f);float checkpointX=G.strokes[sid].pts[G.strokes[sid].n-1].x,checkpointY=G.strokes[sid].pts[G.strokes[sid].n-1].y;end_stroke();check(G.lastWriteValid&&fabsf(G.lastWriteX-checkpointX)<.01f&&fabsf(G.lastWriteY-checkpointY)<.01f,"last-writing checkpoint captures final pen location");G.offX-=900;G.offY-=500;check(write_checkpoint_away(),"return-to-writing option appears after moving away");handle_ui(UI_RETURN_WRITE,tm);check(!write_checkpoint_away(),"return-to-writing restores saved camera");save_workspace();G.lastWriteValid=0;load_workspace();check(G.lastWriteValid&&fabsf(G.lastWriteX-checkpointX)<.01f,"last-writing checkpoint persists per project");selection_set_one(SEL_STROKES,sid);check(!selection_gesture_contains(220,220,250,250),"strokes cannot be pinch-resized");selection_set_one(SEL_FRAME,0);check(!selection_gesture_contains(120,140,460,340),"frames cannot be pinch-resized");G.selectedFrame=0;
 G.measureN=1;G.measures[0]=(Measure){150,150,200,150,1};
 G.imageN=1;ImageObj*im=&G.images[0];memset(im,0,sizeof(*im));im->pw=2;im->ph=2;im->w=100;im->h=80;im->x=200;im->y=180;im->active=1;im->px=(uint32_t*)malloc(4*sizeof(uint32_t));for(int i=0;i<4;i++)im->px[i]=0xffffff;
 selection_set_one(SEL_IMAGE,0);float sdx=3.25f,sdy=-4.75f;selection_snap_delta(&sdx,&sdy);check(fabsf(sdx-3.25f)<.001f&&fabsf(sdy+4.75f)<.001f,"single-photo drag bypasses object snapping");selection_clear();G.photoMode=0;float pcx=(im->x+im->w*.5f)*G.scale+G.offX,pcy=(im->y+im->h*.5f)*G.scale+G.offY;ev1(&fe,AMOTION_ACTION_DOWN,TOOL_FINGER,pcx,pcy,0);handle_motion((AInputEvent*)&fe);check(G.penHoldArmed&&G.touchHoldMode==2&&G.selectedImage<0,"photo requires finger hold before selection");ev1(&fe,AMOTION_ACTION_UP,TOOL_FINGER,pcx,pcy,0);handle_motion((AInputEvent*)&fe);
 G.selectedFrame=0;check(frame_contents_count(&G.frames[0])>=3,"frame counts ink photo CAD");float oldx=G.frames[0].x,oldix=im->x,oldmx=G.measures[0].ax;frame_move_selected_by(20,30);check(G.frames[0].x==oldx+20&&im->x==oldix+20&&G.measures[0].ax==oldmx+20,"frame moves contents together");
 G.visPhotos=0;save_frames();G.frameN=0;G.frameSizeLocked[0]=0;G.visPhotos=1;load_frames();check(G.frameN==1&&G.visPhotos==0,"frames and layer visibility persist");check(G.frameSizeLocked[0]==1,"frame size lock persists");
 G.visPhotos=1;G.frameRevision++;G.minimapDirty=1;render();int mm=margin_ui(),mw=us(320),mh=us(205),mp=us(14),mt=us(40);float mx=G.screenW-mm-mw+mp+5,my=G.screenH-mm-mh+mt+5;float oldOffX=G.offX;check(minimap_navigate(mx,my),"minimap accepts navigation tap");check(fabsf(G.offX-oldOffX)>.01f,"minimap tap moves camera");
 // Photo angle snapping
 G.selectedImage=0;G.photoMode=1;G.photoAngleSnap=1;float cx=(im->x+im->w*.5f)*G.scale+G.offX,cy=(im->y+im->h*.5f)*G.scale+G.offY;float half=60;check(photo_begin_gesture(cx-half,cy,cx+half,cy),"photo gesture starts");photo_update_gesture(cx-half,cy-25,cx+half,cy+25);float step=15.0f*PI/180.0f;float q=im->rot/step;check(fabsf(q-floorf(q+(q>=0?0.5f:-0.5f)))<.01f,"photo rotation snaps to 15 degrees");
 G.photoAngleSnap=0;float before=im->rot;photo_begin_gesture(cx-half,cy,cx+half,cy);photo_update_gesture(cx-half,cy-17,cx+half,cy+23);check(fabsf(im->rot-before)>.001f,"photo free rotation works when snap off");
 // Notes/shapes/search
 add_note_at_center(NOTE_STICKY);check(G.noteN==1&&G.editorOpen,"sticky creates and opens editor");G.editorOpen=0;copy_text_local(G.notes[0].text,96,"ENGINE ROOM");copy_text_local(G.searchQuery,64,"engine");ObjRef sr[6];check(search_collect(sr,6)>0&&sr[0].type==SEL_NOTE,"search finds typed canvas note");
 add_note_at_center(NOTE_TEXT);G.editorOpen=0;NoteObj*tn=&G.notes[G.noteN-1];float shortW=tn->w,shortH=tn->h;copy_text_local(tn->text,96,"A substantially longer line of text that should make the text object wider");note_autosize(tn);check(tn->w>shortW,"text object grows horizontally with content");copy_text_local(tn->text,96,"one\ntwo\nthree\nfour\nfive");note_autosize(tn);check(tn->h>shortH,"text object grows vertically with multiline content");selection_set_one(SEL_NOTE,G.noteN-1);handle_ui(UI_SELECTION_MORE,tm);check(G.selectionMoreOpen,"selection More opens action menu");int wasLocked=tn->locked;handle_ui(UI_SELECTION_LOCK,tm);check(tn->locked!=wasLocked&&!G.selectionMoreOpen,"selection More lock action is wired");
 G.shapeType=SHAPE_RECT;G.liveShape=(ShapeObj){100,100,240,180,0,4,0,1,SHAPE_RECT,0};G.shapeDrawing=1;commit_live_shape();check(G.shapeN==1,"shape commit");
 // Selection duplicate includes photo, CAD, notes, shapes.
 selection_clear();G.selectedRefs[0]=(ObjRef){SEL_IMAGE,0};G.selectedRefs[1]=(ObjRef){SEL_MEASURE,0};G.selectedRefs[2]=(ObjRef){SEL_NOTE,0};G.selectedRefs[3]=(ObjRef){SEL_SHAPE,0};G.selectedRefN=4;G.selectionType=SEL_GROUP;int oi=G.imageN,om=G.measureN,on=G.noteN,os=G.shapeN;selection_duplicate();check(G.imageN==oi+1&&G.measureN==om+1&&G.noteN==on+1&&G.shapeN==os+1,"duplicate supports mixed objects");
 // Project names and duplicate-to-empty-slot.
 copy_text_local(G.projectNames[G.projectIndex],32,"V3 Test");save_project_prefs();int dup=duplicate_current_project();check(dup>=0&&G.projectIndex==dup,"project duplicate switches to copy");check(contains_ci(G.projectNames[G.projectIndex],"copy"),"project duplicate names copy");
 // Frame PNG export. Ensure there is a frame in duplicated project; if not create one.
 if(G.frameN==0){G.liveFrame=(FrameObj){100,120,400,260,0,0,1};frame_add_live();}G.selectedFrame=0;check(export_selected_frame(),"frame PNG export");char ep[640];snprintf(ep,sizeof(ep),"%s/frame_%d.png",a.internalDataPath,G.frames[0].id);void*pf=fopen(ep,"rb");uint8_t sig[8]={0};if(pf){fread(sig,8,1,pf);fclose(pf);}check(sig[0]==137&&sig[1]=='P'&&sig[2]=='N'&&sig[3]=='G',"export is PNG");
 char keptProjectName[32];copy_text_local(keptProjectName,32,G.projectNames[G.projectIndex]);handle_ui(UI_PROJECT_CLEAR,tm);check(G.strokeN==0&&G.imageN==0&&G.measureN==0&&G.frameN==0&&G.noteN==0&&G.shapeN==0&&G.bookmarkN==0&&G.groupN==0&&G.toast==13,"clear project removes every document object class");check(contains_ci(G.projectNames[G.projectIndex],keptProjectName),"clear project preserves the project identity");clear_document_memory();set_project_paths(G.projectIndex);load_canvas();load_meta();load_images();load_frames();load_workspace();check(G.strokeN==0&&G.imageN==0&&G.measureN==0&&G.frameN==0&&G.noteN==0&&G.shapeN==0,"cleared project stays empty after reload");
 save_all_document();save_project_prefs();cb.onDestroy(&a);free(fw.bits);return fail?1:0; }
