typedef unsigned int GLenum,GLuint,GLbitfield; typedef int GLint,GLsizei; typedef float GLfloat; typedef char GLchar; typedef unsigned char GLboolean; typedef void GLvoid;
void glViewport(GLint x,GLint y,GLsizei w,GLsizei h){} void glClearColor(GLfloat r,GLfloat g,GLfloat b,GLfloat a){} void glClear(GLbitfield m){}
GLuint glCreateShader(GLenum t){return 1;} void glShaderSource(GLuint s,GLsizei n,const GLchar*const*src,const GLint*l){} void glCompileShader(GLuint s){} void glGetShaderiv(GLuint s,GLenum p,GLint*v){if(v)*v=1;} void glGetShaderInfoLog(GLuint s,GLsizei n,GLsizei*l,GLchar*i){} void glDeleteShader(GLuint s){}
GLuint glCreateProgram(void){return 1;} void glAttachShader(GLuint p,GLuint s){} void glBindAttribLocation(GLuint p,GLuint i,const GLchar*n){} void glLinkProgram(GLuint p){} void glGetProgramiv(GLuint p,GLenum q,GLint*v){if(v)*v=1;} void glGetProgramInfoLog(GLuint p,GLsizei n,GLsizei*l,GLchar*i){} void glDeleteProgram(GLuint p){} void glUseProgram(GLuint p){}
GLint glGetUniformLocation(GLuint p,const GLchar*n){return 0;} void glUniform1i(GLint l,GLint v){} void glUniform1f(GLint l,GLfloat v){} void glUniform2f(GLint l,GLfloat a,GLfloat b){} void glUniform3f(GLint l,GLfloat a,GLfloat b,GLfloat c){} void glUniform4f(GLint l,GLfloat a,GLfloat b,GLfloat c,GLfloat d){}
void glGenTextures(GLsizei n,GLuint*t){if(t)*t=1;} void glDeleteTextures(GLsizei n,const GLuint*t){} void glBindTexture(GLenum t,GLuint x){} void glTexParameteri(GLenum t,GLenum p,GLint v){} void glTexImage2D(GLenum t,GLint l,GLint in,GLsizei w,GLsizei h,GLint b,GLenum f,GLenum ty,const GLvoid*d){} void glTexSubImage2D(GLenum t,GLint l,GLint x,GLint y,GLsizei w,GLsizei h,GLenum f,GLenum ty,const GLvoid*d){} void glActiveTexture(GLenum t){} void glPixelStorei(GLenum p,GLint v){}
void glEnableVertexAttribArray(GLuint i){} void glVertexAttribPointer(GLuint i,GLint s,GLenum t,GLboolean n,GLsizei st,const GLvoid*p){} void glDrawArrays(GLenum m,GLint f,GLsizei c){} void glDisableVertexAttribArray(GLuint i){}
 void glGetIntegerv(GLenum p,GLint*v){if(v)*v=8192;}
void glGenBuffers(GLsizei n,GLuint*b){if(b)*b=1;}void glDeleteBuffers(GLsizei n,const GLuint*b){}
void glBindBuffer(GLenum t,GLuint b){}void glBufferData(GLenum t,long n,const void*p,GLenum u){}void glBufferSubData(GLenum t,long o,long n,const void*p){}
void glEnable(GLenum t){}void glDisable(GLenum t){}void glBlendFunc(GLenum a,GLenum b){}void glBlendEquation(GLenum e){}
void glGenFramebuffers(GLsizei n,GLuint*b){if(b)*b=1;}void glDeleteFramebuffers(GLsizei n,const GLuint*b){}void glBindFramebuffer(GLenum t,GLuint b){}
void glFramebufferTexture2D(GLenum a,GLenum b,GLenum c,GLuint d,GLint e){}GLenum glCheckFramebufferStatus(GLenum t){return 0x8CD5;}void glScissor(GLint x,GLint y,GLsizei w,GLsizei h){}
